apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-oss
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "ecloud/oss"
    options:
      bucket: "sigma-data"
      endpoint: "eos.hubei-3-internal.cmecloud.cn"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
      akId: ""
      akSecret: ""
